// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJg5KNNTBQrxMQaH-1JthqcQWlQtgHLM',
    appId: '1:1042481604836:web:5b1452fd1c06cbfa22a4f1',
    messagingSenderId: '1042481604836',
    projectId: 'bookmyturf-bf932',
    authDomain: 'bookmyturf-bf932.firebaseapp.com',
    storageBucket: 'bookmyturf-bf932.firebasestorage.app',
    measurementId: 'G-DJSTDDPH25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVE-yRYrR9LZZ5tQMS7g4LBtbIA03RvLw',
    appId: '1:1042481604836:android:51e6889f4ae4707c22a4f1',
    messagingSenderId: '1042481604836',
    projectId: 'bookmyturf-bf932',
    storageBucket: 'bookmyturf-bf932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiUffovBwCweyqPwCRAIPlmkHG9d4QKag',
    appId: '1:1042481604836:ios:e1fef60afd94c82d22a4f1',
    messagingSenderId: '1042481604836',
    projectId: 'bookmyturf-bf932',
    storageBucket: 'bookmyturf-bf932.firebasestorage.app',
    androidClientId: '1042481604836-lp0gkdodnilhccdlif7rjatpu8vfs6pq.apps.googleusercontent.com',
    iosClientId: '1042481604836-e1a8ifumnrrs8lrfthomap3abfjd0eqf.apps.googleusercontent.com',
    iosBundleId: 'com.palindustries.rentmyturf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiUffovBwCweyqPwCRAIPlmkHG9d4QKag',
    appId: '1:1042481604836:ios:e1fef60afd94c82d22a4f1',
    messagingSenderId: '1042481604836',
    projectId: 'bookmyturf-bf932',
    storageBucket: 'bookmyturf-bf932.firebasestorage.app',
    androidClientId: '1042481604836-lp0gkdodnilhccdlif7rjatpu8vfs6pq.apps.googleusercontent.com',
    iosClientId: '1042481604836-e1a8ifumnrrs8lrfthomap3abfjd0eqf.apps.googleusercontent.com',
    iosBundleId: 'com.palindustries.rentmyturf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATJg5KNNTBQrxMQaH-1JthqcQWlQtgHLM',
    appId: '1:1042481604836:web:fdc7e08cb31a2c7422a4f1',
    messagingSenderId: '1042481604836',
    projectId: 'bookmyturf-bf932',
    authDomain: 'bookmyturf-bf932.firebaseapp.com',
    storageBucket: 'bookmyturf-bf932.firebasestorage.app',
    measurementId: 'G-HHLPRSB1GP',
  );
}
